---
title: "FAIR COVID-19 US County Forecasts (projections by Facebook AI)"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: rows
    social: menu
    source_code: embed
---
```{r global, include = F}
suppressWarnings(suppressPackageStartupMessages(library(tidyverse)))
suppressWarnings(suppressPackageStartupMessages(library(colorspace)))
suppressWarnings(suppressPackageStartupMessages(library(zoo)))
suppressWarnings(suppressPackageStartupMessages(library(fpp2)))
options(warn = -1)
```

```{r data}
df.real <- read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')

source('grab_data.R')

this.file <- list.files()[grep(paste('*.csv', sep = ''), list.files())]

df.proj <- read_csv(this.file)

states <- sort(unique(df.proj$loc2))

cols <- c("#E69F00", "#56B4E9")
```

```{r covid}
observeEvent(input$state, {
  ct <- df.proj %>% 
    filter(loc2 == input$state)
  
  ct <- c('All', sort(unique(ct$loc3)))
  
  updateSelectInput(session, 
                    inputId = "county", 
                    label = "County", 
                    choices = ct)
})

pData <- reactive({
  st <- input$state
  ct <- input$county
  
  if(ct == 'All') {
    df.r <- df.real %>%
      filter(state == st) %>%
      group_by(date) %>%
      summarise(cases = sum(cases)) %>%
      ungroup()
    
    df.p <- df.proj %>%
      filter(loc2 == st) %>%
      group_by(date) %>%
      summarise(estimated_cases = sum(estimated_cases)) %>%
      ungroup()
  } else {
    df.r <- df.real %>% 
      filter(state == st &
               county == ct)
    
    df.p <- df.proj %>%
      filter(loc2 == st &
               loc3 == ct)
  }
  
  df.r <- df.r %>%
    mutate(cases = rollmean(cases, as.numeric(input$smooth), fill = NA))
  
  df.combined <- tibble(date = c(df.r$date, df.p$date), 
                        cases = c(df.r$cases, df.p$estimated_cases), 
                        series = c(rep('actual', length(df.r$date)), 
                                   rep('projection', length(df.p$date))))
  
})

output$p1a <- renderPlot({
  df.t <- pData() %>%
    group_by(series) %>%
    mutate(cases = cases - lag(cases)) %>%
    ungroup()
  
  ggplot(df.t, aes(x = date, 
                   y = cases, 
                   color = series,
                   fill = series)) +
    geom_point(size = 4.5, 
               alpha = 0.5, 
               shape = 21) +
    ylab('daily cases') + 
    scale_color_manual(
      name = NULL,
      values = darken(cols, 0.3)
    ) +
    scale_fill_manual(
      name = NULL,
      values = cols
    ) +
    theme_minimal(20) +
    theme(
      legend.position = "top",
      legend.justification = "right",
      legend.text = element_text(size = 14),
      legend.box.spacing = unit(0, "pt")
    )
})

output$p1b <- renderPlot({
  ggplot(pData(), aes(x = date, 
                      y = cases, 
                      color = series,
                      fill = series)) +
    geom_point(size = 4.5, 
               alpha = 0.5, 
               shape = 21) +
    ylab('aggregate cases') +
    scale_color_manual(
      name = NULL,
      values = darken(cols, 0.3)
    ) +
    scale_fill_manual(
      name = NULL,
      values = cols
    ) +
    theme_minimal(20) +
    theme(
      legend.position = "top",
      legend.justification = "right",
      legend.text = element_text(size = 14),
      legend.box.spacing = unit(0, "pt")
    )
})
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("state", 
            label = "State",
            choices = states)

selectInput("county", 
            label = "County",
            choices = NULL)

sliderInput("smooth", 
            label = "Smoothing window (days)",
            min = 1, 
            max = 14, 
            value = 1
)
```

Column
-----------------------------------------------------------------------

### Daily Cases

```{r}
plotOutput("p1a")
```

Column
-----------------------------------------------------------------------

### Aggregate Cases

```{r}
plotOutput("p1b")
```
